name: Build & Release Updater

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Read version from build_req.json
      id: version
      run: |
        version=$(jq -r .version ./build_req.json)
        commit_id=$(git rev-parse --short HEAD)
        new_version="${version}-${commit_id}"
        current_version_code=$(grep versionCode ./app/build.gradle.kts | awk '{print $2}')
        new_version_code=$((current_version_code + 1))
        
        echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
        echo "NEW_VERSION_CODE=${new_version_code}" >> $GITHUB_ENV
        
    - name: Update versionName in build.gradle.kts
      run: |
        sed -i "s/versionName = \".*\"/versionName = \"${{ env.NEW_VERSION }}\"/" app/build.gradle.kts
        sed -i "s/versionCode = .*/versionCode = ${NEW_VERSION_CODE}/" app/build.gradle.kts

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.NEW_VERSION }}
        files: ./app/build/outputs/apk/release/app-release.apk
        release_name: ${{ steps.version.outputs.version }}
        body: '${{ steps.version.outputs.version }}'
        token: ${{ secrets.GITHUB_TOKEN }}
